import { FormEvent, MouseEvent, useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api } from '../../api/client'

export function BrowserPage(){
 const{projectId=''}=useParams();const qc=useQueryClient();const[sid,setSid]=useState('');const[url,setUrl]=useState('');const[error,setError]=useState('');const[frame,setFrame]=useState('');const[connected,setConnected]=useState(false);const stage=useRef<HTMLDivElement>(null);const socket=useRef<WebSocket|null>(null);const editingUrl=useRef(false);const sessions=useQuery({queryKey:['browser',projectId],queryFn:()=>api.listBrowserSessions(projectId),refetchInterval:5000});useEffect(()=>{if(!sid&&sessions.data?.[0]){setSid(sessions.data[0].id);setUrl(sessions.data[0].url)}},[sessions.data,sid]);useEffect(()=>{if(!sid)return;const protocol=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${protocol}://${location.host}/api/v1/projects/${projectId}/browser/sessions/${sid}/stream`);socket.current=ws;ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='frame'){setFrame(`data:image/png;base64,${data.image}`);if(!editingUrl.current)setUrl(data.session.url);setError('');qc.setQueryData(['browser',projectId],(old:typeof sessions.data)=>old?.map(item=>item.id===data.session.id?{...item,...data.session}:item))}if(data.type==='error')setError(data.message)};return()=>{ws.close();socket.current=null;setFrame('');setConnected(false)}},[sid,projectId,qc]);const send=(action:Record<string,unknown>)=>socket.current?.readyState===WebSocket.OPEN&&socket.current.send(JSON.stringify(action));const create=useMutation({mutationFn:()=>api.createBrowserSession(projectId),onSuccess:session=>{setSid(session.id);setUrl(session.url);void qc.invalidateQueries({queryKey:['browser',projectId]})}});const navigate=useMutation({mutationFn:()=>api.navigateBrowser(projectId,sid,url),onSuccess:session=>{editingUrl.current=false;setUrl(session.url);void qc.invalidateQueries({queryKey:['browser',projectId]})}});const close=useMutation({mutationFn:()=>api.closeBrowserSession(projectId,sid),onSuccess:()=>{setSid('');void qc.invalidateQueries({queryKey:['browser',projectId]})}});const active=sessions.data?.find(x=>x.id===sid);function submit(e:FormEvent){e.preventDefault();setError('');if(!/^https?:\/\//i.test(url)){setError('Use an http:// or https:// URL inside the project scope.');return}navigate.mutate()}function click(e:MouseEvent){if(!stage.current)return;const rect=stage.current.getBoundingClientRect();const scaleX=(active?.viewport_width??1280)/rect.width;const scaleY=(active?.viewport_height??800)/rect.height;send({type:'click',x:(e.clientX-rect.left)*scaleX,y:(e.clientY-rect.top)*scaleY})}
 return <main className="page feature-page browser-page"><header className="page-header"><div><p className="eyebrow">Controlled browser</p><h1>Browser</h1><p className="muted">Live browser session routed through AWE’s proxy.</p></div><button onClick={()=>create.mutate()} disabled={create.isPending}>{create.isPending?'Starting…':'New session'}</button></header><section className="browser-toolbar panel"><select value={sid} onChange={e=>{setSid(e.target.value);const s=sessions.data?.find(x=>x.id===e.target.value);if(s)setUrl(s.url)}}><option value="">Select a session</option>{sessions.data?.map(s=><option value={s.id} key={s.id}>{s.title||'New tab'} · {s.id.slice(0,8)}</option>)}</select><form onSubmit={submit}><input value={url} onChange={e=>{editingUrl.current=true;setUrl(e.target.value)}} placeholder="https://target.example" disabled={!sid}/><button disabled={!sid||navigate.isPending}>{navigate.isPending?'Loading…':'Go'}</button></form>{sid&&<><button onClick={()=>send({type:'reload'})}>Reload</button><button className="danger" onClick={()=>close.mutate()}>Close</button></>}</section>{(error||create.isError||navigate.isError)&&<p className="error">{error||((create.error||navigate.error) as Error)?.message}</p>}{active&&<section className="browser-stage panel"><div className="browser-stage-head"><span>{active.title||'Loading'} · {active.url}</span><small>{connected?'● Live':'○ Connecting'}</small></div><div ref={stage} className="browser-frame" onClick={click} onWheel={e=>send({type:'scroll',x:0,y:e.deltaY})} tabIndex={0} onKeyDown={e=>{e.preventDefault();send({type:'press',key:e.key})}}>{frame?<img src={frame} alt="Live managed browser view"/>:<div className="empty">Waiting for browser frame…</div>}</div><p className="muted">Click the browser view and use your keyboard. Requests appear in Site Map and HTTP History.</p></section>}{!active&&<div className="panel empty">Create a browser session to begin.</div>}</main>
}
