import { FormEvent, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type IntruderJob, type IntruderResult } from '../../api/client'

const modes = [{ key: 'sniper', label: 'Sniper' }, { key: 'battering_ram', label: 'Battering Ram' }, { key: 'pitchfork', label: 'Pitchfork' }, { key: 'cluster_bomb', label: 'Cluster Bomb' }]
function errorText(error: unknown) { return error instanceof Error ? error.message : 'Request failed' }
function markers(value: string) { return [...value.matchAll(/§([^§]*)§/g)].map(match => match[1]) }

export function IntruderPage(){
 const{projectId=''}=useParams();const location=useLocation();const navigate=useNavigate();const qc=useQueryClient();const incoming=(location.state as {request?:{method?:string;url?:string;headers?:unknown;body?:string}}|null)?.request
 const[method,setMethod]=useState(incoming?.method||'GET');const[url,setUrl]=useState(incoming?.url||'');const[headers,setHeaders]=useState(JSON.stringify(incoming?.headers??{Accept:'*/*'},null,2));const[body,setBody]=useState(incoming?.body||'');const[mode,setMode]=useState('sniper');const[payloadSets,setPayloadSets]=useState<string[][]>([['admin','test','backup']]);const[concurrency,setConcurrency]=useState(5);const[timeout,setTimeoutValue]=useState(20);const[redirects,setRedirects]=useState(false);const[filter,setFilter]=useState('');const[selected,setSelected]=useState<IntruderResult|null>(null);const[selectedJobId,setSelectedJobId]=useState('');const[detail,setDetail]=useState<'request'|'response'|'render'>('request');const[error,setError]=useState('');const[fileSet,setFileSet]=useState(0);const fileRef=useRef<HTMLInputElement>(null)
 const jobs=useQuery({queryKey:['intruder',projectId,'jobs'],queryFn:()=>api.listIntruderJobs(projectId),refetchInterval:q=>q.state.data?.some(job=>['queued','running','cancelling'].includes(job.status))?1000:false});const activeJob=jobs.data?.find(job=>['queued','running','cancelling'].includes(job.status));const job=jobs.data?.find(item=>item.id===selectedJobId)||activeJob||jobs.data?.[0];const run=useMutation({mutationFn:()=>{let parsed:Record<string,string>;try{parsed=JSON.parse(headers)}catch{throw new Error('Headers must be valid JSON')}return api.startIntruderJob(projectId,{method,url,headers:parsed,body,payloads:payloadSets[0]||[],payload_sets:payloadSets,attack_mode:mode,placeholder:'§payload§',concurrency,timeout_seconds:timeout,follow_redirects:redirects})},onSuccess:()=>{setSelectedJobId('');void qc.invalidateQueries({queryKey:['intruder',projectId,'jobs']})}});const cancel=useMutation({mutationFn:(id:string)=>api.cancelIntruderJob(projectId,id),onSuccess:()=>void qc.invalidateQueries({queryKey:['intruder',projectId,'jobs']})})
 useEffect(()=>{const saved=localStorage.getItem(`awe-intruder-${projectId}`);if(saved&&!incoming)try{const state=JSON.parse(saved);setMethod(state.method);setUrl(state.url);setHeaders(state.headers);setBody(state.body);setMode(state.mode);setPayloadSets(state.payloadSets);setConcurrency(state.concurrency);setTimeoutValue(state.timeout);setRedirects(state.redirects)}catch{/* ignore stale state */}},[]);useEffect(()=>{localStorage.setItem(`awe-intruder-${projectId}`,JSON.stringify({method,url,headers,body,mode,payloadSets,concurrency,timeout,redirects}))},[projectId,method,url,headers,body,mode,payloadSets,concurrency,timeout,redirects])
 const allPositions=markers(`${url}\n${body}`);const rows=useMemo(()=>job?.results.filter(row=>`${row.payload} ${row.status_code} ${row.length} ${row.error}`.toLowerCase().includes(filter.toLowerCase()))??[],[job,filter]);const current=selected??rows[0]
 function autoMark(){setUrl(old=>{try{const parsed=new URL(old);for(const key of parsed.searchParams.keys())parsed.searchParams.set(key,`§${parsed.searchParams.get(key)||''}§`);return parsed.toString()}catch{return old.replace(/=([^&\s#]+)/g,'=§$1§')}});setBody(old=>old.replace(/=([^&\s&]+)/g,'=§$1§'))}function clearMarks(){setUrl(old=>old.replaceAll('§',''));setBody(old=>old.replaceAll('§',''))}function addSet(){setPayloadSets(old=>[...old,['admin','test','backup']])}function updateSet(index:number,value:string){setPayloadSets(old=>old.map((set,i)=>i===index?value.split('\n').filter(Boolean):set))}function loadFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(file){file.text().then(text=>updateSet(fileSet,text));setFileSet(0)}event.target.value=''}function submit(event:FormEvent){event.preventDefault();setError('');if(!allPositions.length){setError('Mark at least one position with §…§.');return}if(!payloadSets.some(set=>set.length)){setError('Add at least one payload.');return}run.mutate()}function exportCsv(){const csv=['#,Payload,Status,Length,Time (ms),Error',...rows.map(r=>[r.sequence,r.payload,r.status_code,r.length,r.elapsed_ms,r.error].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');const href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=href;a.download='intruder-results.csv';a.click();URL.revokeObjectURL(href)}
 return <main className="page feature-page intruder-page"><Link className="back-link" to={`/projects/${projectId}`}>← Project workspace</Link><header className="page-header"><div><p className="eyebrow">Automated manual testing</p><h1>Intruder</h1><p className="muted">Fuzz marked positions with Sniper, Battering Ram, Pitchfork, or Cluster Bomb attacks.</p></div><span className={activeJob?'live-dot active':'live-dot'}>{activeJob?`${activeJob.status} · ${activeJob.completed}/${activeJob.total}`:job?`${job.status} · ${job.completed}/${job.total}`:'Idle'}</span></header>
 <form className="intruder-workbench" onSubmit={submit}><section className="panel intruder-request"><header><b>Request positions</b><nav><button type="button" onClick={autoMark}>Auto §</button><button type="button" onClick={clearMarks}>Clear §</button><small>{allPositions.length} position{allPositions.length===1?'':'s'}</small></nav></header><div className="request-line"><select value={method} onChange={e=>setMethod(e.target.value)}>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(x=><option key={x}>{x}</option>)}</select><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://target.test/users?id=§value§"/></div><label>Headers (JSON)<textarea value={headers} onChange={e=>setHeaders(e.target.value)}/></label><label>Body<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={'{"username":"§value§"}'}/></label></section><aside className="panel intruder-payloads"><h3>Attack mode</h3><select value={mode} onChange={e=>setMode(e.target.value)}>{modes.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select><p className="muted">Sniper cycles positions; Battering Ram reuses one value; Pitchfork zips sets; Cluster Bomb tries every combination.</p><h3>Payload sets</h3>{payloadSets.map((set,index)=><label className="intruder-payload-set" key={index}><span>Set {index+1} · {set.length} payloads</span><textarea value={set.join('\n')} onChange={e=>updateSet(index,e.target.value)} /><div><button type="button" onClick={()=>{setFileSet(index);fileRef.current?.click()}}>Load file</button>{index>0&&<button type="button" onClick={()=>setPayloadSets(old=>old.filter((_,i)=>i!==index))}>Remove</button>}</div></label>)}<input hidden ref={fileRef} type="file" accept=".txt" onChange={loadFile}/><button type="button" onClick={addSet}>＋ Add payload set</button><label>Concurrency<input type="number" min="1" max="25" value={concurrency} onChange={e=>setConcurrency(Number(e.target.value))}/></label><label>Timeout (seconds)<input type="number" min="1" max="120" value={timeout} onChange={e=>setTimeoutValue(Number(e.target.value))}/></label><label className="result-toggle"><input type="checkbox" checked={redirects} onChange={e=>setRedirects(e.target.checked)}/> Follow redirects</label><button disabled={!!activeJob||run.isPending||!payloadSets.some(set=>set.length)}>{run.isPending?'Starting…':'▶ Start attack'}</button>{activeJob&&<button type="button" className="danger" onClick={()=>cancel.mutate(activeJob.id)}>■ Stop</button>}</aside></form>{(error||run.isError||cancel.isError)&&<p className="error">{error||errorText(run.error||cancel.error)}</p>}
 {jobs.data&&jobs.data.length>0&&<section className="panel intruder-history"><header><b>Attack history</b><span>{jobs.data.length} runs</span></header>{jobs.data.map(item=><button className={item.id===job?.id?'selected':''} key={item.id} onClick={()=>{setSelectedJobId(item.id);setSelected(item.results[0]||null)}}><b>{item.status}</b><span>{item.completed}/{item.total} requests · {new Date(item.created_at).toLocaleString()}</span></button>)}</section>}
 {job&&<section className="intruder-results"><div className="panel intruder-result-table"><header><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter results…"/><button onClick={exportCsv}>Export CSV</button></header><div><table><thead><tr><th>#</th><th>Payload</th><th>Status</th><th>Length</th><th>Time</th><th>Error</th></tr></thead><tbody>{rows.map(row=><tr className={current?.sequence===row.sequence?'selected':''} onClick={()=>setSelected(row)} key={row.sequence}><td>{row.sequence}</td><td><code>{row.payload}</code></td><td>{row.status_code||'—'}</td><td>{row.length}</td><td>{row.elapsed_ms} ms</td><td>{row.error}</td></tr>)}</tbody></table></div></div><section className="panel intruder-detail">{current?<><header><nav>{(['request','response','render'] as const).map(x=><button className={detail===x?'selected':''} onClick={()=>setDetail(x)} key={x}>{x}</button>)}</nav><button onClick={()=>{let parsed:Record<string,string>={};try{parsed=JSON.parse(headers)}catch{}navigate(`/projects/${projectId}/repeater`,{state:{request:{method,url:current.request_url,headers:parsed,body:current.request_body}}})}}>Send to Repeater</button></header>{detail==='request'&&<pre>{`${method} ${current.request_url}\n\n${current.request_body}`}</pre>}{detail==='response'&&<pre>{`HTTP ${current.status_code}\n${Object.entries(current.response_headers).map(([k,v])=>`${k}: ${v}`).join('\n')}\n\n${current.response_body}`}</pre>}{detail==='render'&&(String(current.response_headers['content-type']??'').includes('html')?<iframe sandbox="" srcDoc={current.response_body}/>:<div className="empty">HTML responses can be rendered.</div>)}</>:<div className="empty">Select a result.</div>}</section></section>}</main>
}
