import { FormEvent, useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api } from '../../api/client'

export function RepeaterPage() {
  const { projectId = '' } = useParams(); const [method, setMethod] = useState('GET'); const [url, setUrl] = useState(''); const [headers, setHeaders] = useState('{\n  "Accept": "*/*"\n}'); const [body, setBody] = useState(''); const [inputError, setInputError] = useState('')
  const send = useMutation({ mutationFn: () => { let parsed: Record<string,string>; try { parsed = JSON.parse(headers || '{}') } catch { throw new Error('Headers must be a valid JSON object') } return api.sendRepeater(projectId, { method, url, headers: parsed, body }) } })
  function submit(event: FormEvent) { event.preventDefault(); setInputError(''); if (!url) { setInputError('Enter a URL'); return } send.mutate() }
  return <main className="page feature-page"><Link className="back-link" to={`/projects/${projectId}`}>← Project workspace</Link><header className="page-header"><div><p className="eyebrow">Manual testing</p><h1>Repeater</h1><p className="muted">Edit and resend scoped HTTP requests through the backend.</p></div></header><form className="repeater-target panel" onSubmit={submit}><select value={method} onChange={(e) => setMethod(e.target.value)}>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map((item) => <option key={item}>{item}</option>)}</select><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://target.example/api"/><button disabled={send.isPending}>{send.isPending ? 'Sending…' : 'Send'}</button></form><section className="editor-grid repeater-editors"><label className="panel editor-panel"><span>Headers (JSON)</span><textarea value={headers} onChange={(e) => setHeaders(e.target.value)} spellCheck={false}/></label><label className="panel editor-panel"><span>Request body</span><textarea value={body} onChange={(e) => setBody(e.target.value)} spellCheck={false}/></label></section>{(inputError || send.isError) && <p className="error">{inputError || send.error?.message}</p>}{send.data && <section className="panel repeater-response"><header><b>{send.data.status_code} {send.data.reason}</b><span>{send.data.elapsed_ms} ms{send.data.body_truncated ? ' · truncated' : ''}</span></header><div className="editor-grid"><article><span>Response headers</span><pre>{JSON.stringify(send.data.headers, null, 2)}</pre></article><article><span>Response body</span><pre>{send.data.body}</pre></article></div></section>}</main>
}
