import { FormEvent, useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useLocation, useParams } from 'react-router-dom'
import { api, InterceptRequest } from '../../api/client'
import { createClientId } from './httpCodeView'

function Head({ id, title, detail }: { id:string;title:string;detail:string }) { return <><Link className="back-link" to={`/projects/${id}`}>← Project workspace</Link><header className="page-header"><div><p className="eyebrow">Manual testing</p><h1>{title}</h1><p className="muted">{detail}</p></div></header></> }
function errorText(error: unknown) { return error instanceof Error ? error.message : 'Request failed' }

export function IntruderPage() {
  const {projectId=''}=useParams();const location=useLocation();const incoming=(location.state as {request?:{method?:string;url?:string;headers?:unknown;body?:string}}|null)?.request; const[method,setMethod]=useState(incoming?.method||'GET');const[url,setUrl]=useState(incoming?.url||'');const[headers,setHeaders]=useState(JSON.stringify(incoming?.headers??{Accept:'*/*'},null,2));const[body,setBody]=useState(incoming?.body||'');const[payloads,setPayloads]=useState('admin\ntest\nbackup');const[error,setError]=useState('')
  const run=useMutation({mutationFn:()=>{let parsed:Record<string,string>;try{parsed=JSON.parse(headers)}catch{throw new Error('Headers must be valid JSON')}return api.runIntruder(projectId,{method,url,headers:parsed,body,payloads:payloads.split('\n').map(x=>x.trim()).filter(Boolean),placeholder:'§payload§'})}})
  function submit(e:FormEvent){e.preventDefault();setError('');if(!url.includes('§payload§')&&!body.includes('§payload§')){setError('Add §payload§ to the URL or body.');return}run.mutate()}
  return <main className="page feature-page"><Head id={projectId} title="Intruder" detail="Run a bounded payload attack against a scoped request."/><form className="intruder-layout" onSubmit={submit}><section className="panel attack-editor"><div className="request-line"><select value={method} onChange={e=>setMethod(e.target.value)}>{['GET','POST','PUT','PATCH','DELETE'].map(x=><option key={x}>{x}</option>)}</select><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://target.test/users/§payload§"/></div><label>Headers (JSON)<textarea value={headers} onChange={e=>setHeaders(e.target.value)}/></label><label>Body<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder={'{"username":"§payload§"}'}/></label></section><aside className="panel payload-editor"><label>Payloads — one per line<textarea value={payloads} onChange={e=>setPayloads(e.target.value)}/></label><span>{payloads.split('\n').filter(Boolean).length} / 100 payloads</span><button disabled={run.isPending}>{run.isPending?'Running…':'Start attack'}</button></aside></form>{(error||run.isError)&&<p className="error">{error||errorText(run.error)}</p>}{run.data&&<section className="panel result-table"><header><b>Attack results</b><span>{run.data.length} requests</span></header><div className="table-scroll"><table><thead><tr><th>#</th><th>Payload</th><th>Status</th><th>Length</th><th>Time</th><th>Error</th></tr></thead><tbody>{run.data.map(row=><tr key={row.sequence}><td>{row.sequence}</td><td><code>{row.payload}</code></td><td>{row.status_code||'—'}</td><td>{row.length}</td><td>{row.elapsed_ms} ms</td><td>{row.error}</td></tr>)}</tbody></table></div></section>}</main>
}

export function WebSocketsPage(){
 const{projectId=''}=useParams();const[selected,setSelected]=useState('');const[url,setUrl]=useState('');const[message,setMessage]=useState('');const[binary,setBinary]=useState(false);const[live,setLive]=useState(false);const[liveFrames,setLiveFrames]=useState<Array<{id:string;direction:string;opcode_name:string;payload_text:string;payload_len:number}>>([]);const[status,setStatus]=useState('Disconnected');const socketRef=useRef<WebSocket|null>(null);const connections=useQuery({queryKey:['ws',projectId],queryFn:()=>api.listWebSockets(projectId),refetchInterval:3000});const frames=useQuery({queryKey:['ws',projectId,selected,'frames'],queryFn:()=>api.listWebSocketFrames(projectId,selected),enabled:!!selected,refetchInterval:2000});const send=useMutation({mutationFn:()=>api.sendWebSocket(projectId,url,message)})
 useEffect(()=>()=>{socketRef.current?.close()},[])
 function disconnect(){socketRef.current?.close();socketRef.current=null;setLive(false);setStatus('Disconnected')}
 function connect(){if(!url.trim())return;disconnect();try{const socket=new WebSocket(url.trim());socketRef.current=socket;setStatus('Connecting…');socket.onopen=()=>{setLive(true);setStatus('Connected')};socket.onmessage=event=>{const text=typeof event.data==='string'?event.data:`Binary frame (${event.data.byteLength||0} bytes)`;setLiveFrames(old=>[...old,{id:createClientId(),direction:'server_to_client',opcode_name:typeof event.data==='string'?'text':'binary',payload_text:text,payload_len:typeof event.data==='string'?new TextEncoder().encode(event.data).length:event.data.byteLength||0}])};socket.onerror=()=>setStatus('Connection error');socket.onclose=()=>{setLive(false);setStatus('Disconnected')}}catch(error){setStatus(error instanceof Error?error.message:'Invalid WebSocket URL')}}
 function sendFrame(event:FormEvent){event.preventDefault();if(!socketRef.current||socketRef.current.readyState!==WebSocket.OPEN){setStatus('Connect before sending');return}try{if(binary){const hex=message.replace(/\s/g,'');if(!/^[0-9a-f]*$/i.test(hex)||hex.length%2){setStatus('Binary payload must be even-length hexadecimal');return}const bytes=new Uint8Array(hex.match(/.{2}/g)?.map(value=>parseInt(value,16))||[]);socketRef.current.send(bytes);setLiveFrames(old=>[...old,{id:createClientId(),direction:'client_to_server',opcode_name:'binary',payload_text:hex,payload_len:bytes.length}])}else{socketRef.current.send(message);setLiveFrames(old=>[...old,{id:createClientId(),direction:'client_to_server',opcode_name:'text',payload_text:message,payload_len:new TextEncoder().encode(message).length}])}}catch(error){setStatus(error instanceof Error?error.message:'Send failed')}}
 const storedFrames=frames.data??[];const visibleFrames=live?liveFrames:storedFrames
 return <main className="page feature-page"><Head id={projectId} title="WebSocket Inspector" detail="Review captured frames, maintain live connections, and send text or binary payloads."/><section className="ws-grid"><div className="panel ws-connections"><header><b>Connections</b><span>{connections.data?.length??0}</span></header><div className="ws-connection-actions"><button onClick={()=>void connections.refetch()}>Refresh</button><button onClick={()=>{setSelected('');setLiveFrames([])}}>Clear view</button></div>{connections.data?.map(c=><button className={selected===c.id?'selected':''} onClick={()=>{disconnect();setLiveFrames([]);setSelected(c.id)}} key={c.id}><b>{c.host}</b><span>{c.path}</span><small>{c.frame_count} frames · {c.closed_at?'closed':'open'}</small></button>)}</div><div className="panel ws-frames"><header className="ws-frame-header"><b>{live?'Live frames':selected?'Captured frames':'Frames'}</b><span className={live?'live-dot active':'live-dot'}>{live?status:'Stored'}</span></header>{visibleFrames.map(f=><article className={f.direction.includes('client')?'outbound':'inbound'} key={f.id}><header><b>{f.direction.includes('client')?'→ Sent':'← Received'}</b><small>{f.opcode_name} · {f.payload_len} B</small></header><pre>{f.payload_text}</pre></article>)}{!visibleFrames.length&&<div className="empty">{selected?'No frames captured yet.':'Select a captured connection or connect below.'}</div>}</div></section><form className="panel ws-send" onSubmit={sendFrame}><header><b>Live connection</b><div><button type="button" onClick={connect} disabled={!url||live}>Connect</button><button type="button" className="danger" onClick={disconnect} disabled={!live}>Disconnect</button></div></header><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="wss://target.example/socket"/><label className="ws-binary-toggle"><input type="checkbox" checked={binary} onChange={e=>setBinary(e.target.checked)}/> Send binary (hex)</label><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={binary?'48 65 6c 6c 6f':'Message payload'}/><button disabled={!live}>{binary?'▶ Send Binary':'▶ Send Text'}</button>{status&&<small className="muted">{status}</small>}</form><form className="panel ws-one-shot" onSubmit={e=>{e.preventDefault();send.mutate()}}><b>One-shot backend send</b><button disabled={!url||send.isPending}>{send.isPending?'Connecting…':'Connect & send once'}</button>{send.data&&<pre>{send.data.reply||'(No reply within 10 seconds)'}</pre>}{send.isError&&<p className="error">{errorText(send.error)}</p>}</form></main>
}

function decodeBody(value:string){try{return atob(value)}catch{return ''}}function encodeBody(value:string){return btoa(unescape(encodeURIComponent(value)))}
export function InterceptPage(){
 const{projectId=''}=useParams();const qc=useQueryClient();const[enabled,setEnabled]=useState(false);const[patterns,setPatterns]=useState('');const[selected,setSelected]=useState<InterceptRequest|null>(null);const[headers,setHeaders]=useState('[]');const[body,setBody]=useState('');const pending=useQuery({queryKey:['intercept',projectId],queryFn:()=>api.listPendingIntercepts(projectId),refetchInterval:1000});useEffect(()=>{if(selected&&!pending.data?.some(x=>x.id===selected.id))setSelected(null)},[pending.data,selected]);const configure=useMutation({mutationFn:(next:boolean)=>api.setIntercept(projectId,next,patterns.split('\n').filter(Boolean)),onSuccess:(_,next)=>setEnabled(next)});const resolve=useMutation({mutationFn:(decision:'forward'|'drop')=>{if(!selected)throw new Error('Select a request');let parsed:string[][];try{parsed=JSON.parse(headers)}catch{throw new Error('Headers must be a JSON array')}return api.resolveIntercept(projectId,selected.id,{decision,headers:parsed,body_b64:encodeBody(body)})},onSuccess:()=>{setSelected(null);void qc.invalidateQueries({queryKey:['intercept',projectId]})}});function choose(item:InterceptRequest){setSelected(item);setHeaders(JSON.stringify(item.headers,null,2));setBody(decodeBody(item.body_b64))}
 return <main className="page feature-page"><Head id={projectId} title="Intercept" detail="Pause, edit, forward, or drop live proxy requests."/><section className="panel intercept-toolbar"><button className={enabled?'danger':''} onClick={()=>configure.mutate(!enabled)}>{enabled?'Disable intercept':'Enable intercept'}</button><label>Host patterns (regex, one per line)<textarea value={patterns} onChange={e=>setPatterns(e.target.value)} placeholder="example\\.com$"/></label><span className={enabled?'live-dot active':'live-dot'}>{enabled?'Intercepting':'Off'}</span></section><section className="intercept-grid"><div className="panel intercept-queue"><header><b>Pending requests</b><span>{pending.data?.length??0}</span></header>{pending.data?.map(item=><button className={selected?.id===item.id?'selected':''} onClick={()=>choose(item)} key={item.id}><b>{item.method}</b><span>{item.host}</span><small>{item.url}</small></button>)}</div><div className="panel intercept-editor">{selected?<><h3>{selected.method} {selected.url}</h3><label>Headers<textarea value={headers} onChange={e=>setHeaders(e.target.value)}/></label><label>Body<textarea value={body} onChange={e=>setBody(e.target.value)}/></label><footer><button onClick={()=>resolve.mutate('forward')}>Forward</button><button className="danger" onClick={()=>resolve.mutate('drop')}>Drop</button></footer></>:<div className="empty">Waiting for an intercepted request.</div>}</div></section>{(configure.isError||resolve.isError)&&<p className="error">{errorText(configure.error||resolve.error)}</p>}</main>
}
