FROM golang:1.21-alpine AS builder
RUN go install github.com/tomnomnom/waybackurls@latest

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/waybackurls /usr/local/bin/waybackurls
RUN mkdir /output
ENTRYPOINT ["waybackurls"]
