FROM golang:1.25-alpine AS builder

RUN go install github.com/projectdiscovery/tlsx/cmd/tlsx@latest

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/tlsx /usr/local/bin/tlsx
RUN mkdir -p /output
ENTRYPOINT ["tlsx"]
