FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/tomnomnom/assetfinder.git /assetfinder
WORKDIR /assetfinder
RUN go build -o /go/bin/assetfinder .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/assetfinder /usr/local/bin/assetfinder
RUN mkdir /output
ENTRYPOINT ["assetfinder"]
