FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/assetnote/kiterunner.git /kiterunner
WORKDIR /kiterunner
RUN go build -o /go/bin/kr ./cmd/kiterunner/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/kr /usr/local/bin/kr
RUN mkdir /output
ENTRYPOINT ["kr"]
