FROM python:3.9-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends git ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/maK-/parameth.git /app/parameth
RUN pip install --no-cache-dir -r /app/parameth/requirements.txt
RUN mkdir /output
WORKDIR /app/parameth
ENTRYPOINT ["python3", "parameth.py"]
