FROM golang:1.24-alpine AS builder
RUN go install github.com/j3ssie/metabigor@latest

FROM alpine:3.19
COPY --from=builder /go/bin/metabigor /usr/local/bin/metabigor
RUN mkdir /output
ENTRYPOINT ["metabigor"]
