FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/tomnomnom/kxss.git /kxss
WORKDIR /kxss
RUN go build -o /go/bin/kxss .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/kxss /usr/local/bin/kxss
RUN mkdir /output
ENTRYPOINT ["kxss"]
