FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/assetnote/kiterunner/cmd/kr@latest

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/kr /usr/local/bin/kr
RUN mkdir /output
ENTRYPOINT ["kr"]
