FROM golang:1.26-alpine AS builder

RUN go install github.com/sa7mon/s3scanner@latest

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/s3scanner /usr/local/bin/s3scanner
RUN mkdir -p /output
ENTRYPOINT ["s3scanner"]
