FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/LukaSikic/subzy.git /subzy
WORKDIR /subzy
RUN go build -o /go/bin/subzy .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/subzy /usr/local/bin/subzy
RUN mkdir /output
ENTRYPOINT ["subzy"]
