FROM python:3.11-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends git ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir xnLinkFinder
RUN mkdir /output
ENTRYPOINT ["xnLinkFinder"]
