FROM ruby:3.2-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN gem install cewl --no-document
RUN mkdir /output
ENTRYPOINT ["cewl"]
