FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN git clone --depth 1 https://github.com/tomnomnom/waybackurls.git /waybackurls
WORKDIR /waybackurls
RUN go build -o /go/bin/waybackurls .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/waybackurls /usr/local/bin/waybackurls
RUN mkdir /output
ENTRYPOINT ["waybackurls"]
