FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/LukaSikic/subzy@latest

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/subzy /usr/local/bin/subzy
RUN mkdir /output
ENTRYPOINT ["subzy"]
