FROM golang:1.25-alpine AS builder

RUN go install github.com/projectdiscovery/asnmap/cmd/asnmap@latest

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/asnmap /usr/local/bin/asnmap
RUN mkdir -p /output
ENTRYPOINT ["asnmap"]
