FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
RUN go install github.com/KathanP01/Gxss@latest

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/Gxss /usr/local/bin/gxss
RUN mkdir /output
ENTRYPOINT ["gxss"]
