FROM python:3.12-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    git && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git /sqlmap
WORKDIR /sqlmap
RUN mkdir /output
ENTRYPOINT ["python3", "sqlmap.py"]
