FROM python:3.11-slim

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    git dnsutils nmap \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir sublist3r

RUN mkdir /output

ENTRYPOINT ["sublist3r"]
