FROM python:3.12-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    git && rm -rf /var/lib/apt/lists/*
RUN git clone --depth 1 https://github.com/m4ll0k/SecretFinder.git /secretfinder
WORKDIR /secretfinder
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir /output
ENTRYPOINT ["python3", "SecretFinder.py"]
