FROM golang:1.24-alpine AS builder
RUN go install github.com/tomnomnom/assetfinder@latest

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/bin/assetfinder /usr/local/bin/assetfinder
RUN mkdir /output
ENTRYPOINT ["assetfinder"]
