import { FormEvent, useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api } from '../../api/client'

type EventMessage={role:'user'|'assistant';content:string}

export function StreamingAIPage(){
  const {projectId=''}=useParams(); const qc=useQueryClient(); const [cid,setCid]=useState(''); const [input,setInput]=useState(''); const [messages,setMessages]=useState<EventMessage[]>([]); const [events,setEvents]=useState<string[]>([]); const [status,setStatus]=useState('Idle'); const socket=useRef<WebSocket|null>(null)
  const chats=useQuery({queryKey:['ai','conversations',projectId],queryFn:()=>api.listAIConversations(projectId)}); const approvals=useQuery({queryKey:['ai','approvals',projectId],queryFn:()=>api.listAIApprovals(projectId),refetchInterval:2000})
  const detail=useQuery({queryKey:['ai','conversation',projectId,cid],queryFn:()=>api.getAIConversation(projectId,cid),enabled:!!cid})
  useEffect(()=>{if(detail.data)setMessages(detail.data.messages.filter(m=>m.role==='user'||m.role==='assistant').map(m=>({role:m.role as 'user'|'assistant',content:m.content})))},[detail.data])
  useEffect(()=>()=>{socket.current?.close()},[])
  const create=useMutation({mutationFn:()=>api.createAIConversation(projectId),onSuccess:c=>{setCid(c.id);setMessages([]);void qc.invalidateQueries({queryKey:['ai','conversations',projectId]})}}); const resolve=useMutation({mutationFn:(input:{id:string;decision:'approve'|'reject'})=>api.resolveAIApproval(projectId,input.id,input.decision),onSuccess:()=>void qc.invalidateQueries({queryKey:['ai','approvals',projectId]})})
  function send(event:FormEvent){event.preventDefault();const content=input.trim();if(!content||!cid)return;setInput('');setEvents([]);setMessages(old=>[...old,{role:'user',content},{role:'assistant',content:''}]);setStatus('Connecting…');const protocol=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${protocol}://${location.host}/api/v1/projects/${projectId}/ai/conversations/${cid}/stream`);socket.current=ws;ws.onopen=()=>{setStatus('Thinking…');ws.send(JSON.stringify({content}))};ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='token'){setStatus('Streaming…');setMessages(old=>{const next=[...old];const last=next[next.length-1];if(last?.role==='assistant')last.content+=data.text;return next})}else if(data.type==='message_complete'){setStatus('Complete');void qc.invalidateQueries({queryKey:['ai','conversation',projectId,cid]})}else if(data.type==='tool_call'){setStatus(`Using ${data.name}…`);setEvents(old=>[...old,`Tool call: ${data.name}`])}else if(data.type==='tool_result'){setStatus('Processing tool result…');setEvents(old=>[...old,`Tool result: ${data.name||'read-only context'}`])}else if(data.type==='error'){setStatus('Error');setEvents(old=>[...old,`Error: ${data.message}`]);setMessages(old=>{const next=[...old];const last=next[next.length-1];if(last?.role==='assistant')last.content=data.message;return next})}};ws.onerror=()=>setStatus('Connection error');ws.onclose=()=>{if(status!=='Error')setStatus('Idle')}}
  return <main className="page feature-page ai-page"><header className="page-header"><div><p className="eyebrow">AI assistant · realtime</p><h1>AWE Intelligence</h1><p className="muted">Streaming responses with project-scoped context and tool execution events.</p></div><button onClick={()=>create.mutate()}>＋ New chat</button></header>{approvals.data?.map(item=><article className={`panel ai-approval risk-${item.risk}`} key={item.id}><div><b>Approval required: {item.tool_name}</b><pre>{JSON.stringify(item.arguments,null,2)}</pre></div><footer><button onClick={()=>resolve.mutate({id:item.id,decision:'approve'})}>Approve</button><button className="danger" onClick={()=>resolve.mutate({id:item.id,decision:'reject'})}>Reject</button></footer></article>)}<section className="ai-layout"><aside className="panel ai-sidebar"><header><b>Conversations</b><span>{chats.data?.length??0}</span></header>{chats.data?.map(chat=><button className={cid===chat.id?'selected':''} onClick={()=>setCid(chat.id)} key={chat.id}>{chat.title}<small>{new Date(chat.updated_at).toLocaleString()}</small></button>)}</aside><section className="panel ai-chat"><div className="ai-runtime-status"><span className={status==='Streaming…'?'live-dot active':'live-dot'}>{status}</span></div>{events.map((event,index)=><div className="ai-tool-event" key={index}>{event}</div>)}{messages.map((message,index)=><article className={`ai-message ${message.role}`} key={index}><span>{message.role}</span><p>{message.content||'▌'}</p></article>)}{!cid&&<div className="empty">Create a chat to start.</div>}<form onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask AWE to inspect the project…" disabled={!cid}/><button disabled={!cid||!input.trim()}>{status==='Streaming…'?'Stop':'Send'}</button></form></section></section></main>
}
