import { FormEvent, useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api, ProjectSettings } from '../../api/client'

const defaults:ProjectSettings={default_threads:10,default_rate_limit:150,default_concurrency:25,proxy_port:8080,upstream_proxy:''}
function Head({id,title,detail}:{id:string;title:string;detail:string}){return <><Link className="back-link" to={`/projects/${id}`}>← Project workspace</Link><header className="page-header"><div><p className="eyebrow">Administration</p><h1>{title}</h1><p className="muted">{detail}</p></div></header></>}

export function SettingsPage(){const{id=''}={id:useParams().projectId};const q=useQuery({queryKey:['settings',id],queryFn:()=>api.getSettings(id)});const proxy=useQuery({queryKey:['proxy-info'],queryFn:api.getProxyInfo});const[data,setData]=useState(defaults);useEffect(()=>{if(q.data)setData(q.data)},[q.data]);const save=useMutation({mutationFn:()=>api.saveSettings(id,data)});return <main className="page"><Head id={id} title="Settings" detail="Project execution and proxy defaults."/><section className="panel settings-grid">{(['default_threads','default_rate_limit','default_concurrency','proxy_port'] as const).map(key=><label key={key}>{key.replaceAll('_',' ')}<input type="number" value={data[key]} onChange={e=>setData({...data,[key]:Number(e.target.value)})}/></label>)}<label className="wide">Upstream proxy<input value={data.upstream_proxy} onChange={e=>setData({...data,upstream_proxy:e.target.value})} placeholder="http://127.0.0.1:9050"/></label><button onClick={()=>save.mutate()} disabled={save.isPending}>{save.isPending?'Saving…':'Save settings'}</button></section>{save.isSuccess&&<p className="success">Settings saved.</p>}<section className="panel proxy-setup"><h2>External browser proxy</h2><p className="muted">Configure another browser or device to send traffic into this AWE instance. Install the CA certificate first so HTTPS traffic can be inspected.</p>{proxy.data&&<><code>{proxy.data.host}:{proxy.data.port}</code><a className="button" href={proxy.data.certificate_url} download>Download AWE CA certificate</a><ol><li>Set the browser HTTP and HTTPS proxy to the address above.</li><li>Use this project ID as the proxy username: <code>{id}</code> (any password is accepted).</li><li>Install the downloaded <code>awe-proxy-ca.crt</code> as a trusted certificate authority.</li><li>Browse targets; requests will appear in HTTP History and Site Map.</li></ol></>}{proxy.isError&&<p className="error">Proxy configuration is unavailable.</p>}</section></main>}

export function DockerPage(){const{id=''}={id:useParams().projectId};const qc=useQueryClient();const q=useQuery({queryKey:['docker'],queryFn:api.listContainers,refetchInterval:3000});const action=useMutation({mutationFn:({id,remove}:{id:string;remove:boolean})=>remove?api.removeContainer(id):api.stopContainer(id),onSuccess:()=>qc.invalidateQueries({queryKey:['docker']})});return <main className="page"><Head id={id} title="Docker Manager" detail="Monitor and control containers created by AWE."/><section className="container-grid">{q.data?.map(c=><article className="panel container-card" key={c.id}><header><i className={`container-${c.status}`}/><div><b>{c.name}</b><span>{c.image}</span></div></header><footer><span>{c.status}</span><button onClick={()=>action.mutate({id:c.id,remove:false})} disabled={c.status!=='running'}>Stop</button><button onClick={()=>action.mutate({id:c.id,remove:true})}>Remove</button></footer></article>)}</section>{q.data?.length===0&&<div className="panel empty">No AWE containers.</div>}</main>}

export function VaultPage(){const{id=''}={id:useParams().projectId};const qc=useQueryClient();const q=useQuery({queryKey:['vault',id],queryFn:()=>api.listVault(id)});const[name,setName]=useState('');const[value,setValue]=useState('');const[kind,setKind]=useState<'credential'|'api_key'|'token'|'note'>('credential');const[visible,setVisible]=useState<Set<string>>(new Set());const create=useMutation({mutationFn:()=>api.createVault(id,{name,value,kind}),onSuccess:()=>{setName('');setValue('');qc.invalidateQueries({queryKey:['vault',id]})}});const del=useMutation({mutationFn:(item:string)=>api.deleteVault(id,item),onSuccess:()=>qc.invalidateQueries({queryKey:['vault',id]})});function submit(e:FormEvent){e.preventDefault();if(name&&value)create.mutate()}return <main className="page"><Head id={id} title="Vault" detail="Encrypted project credentials, keys, tokens, and notes."/><form className="panel vault-form" onSubmit={submit}><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="credential">Credential</option><option value="api_key">API key</option><option value="token">Token</option><option value="note">Note</option></select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><input type="password" value={value} onChange={e=>setValue(e.target.value)} placeholder="Secret value"/><button>Add</button></form><section className="vault-list">{q.data?.map(item=><article className="panel" key={item.id}><div><span>{item.kind}</span><b>{item.name}</b><code>{visible.has(item.id)?item.value:'••••••••••••'}</code></div><footer><button onClick={()=>setVisible(old=>{const n=new Set(old);n.has(item.id)?n.delete(item.id):n.add(item.id);return n})}>{visible.has(item.id)?'Hide':'Reveal'}</button><button onClick={()=>navigator.clipboard.writeText(item.value)}>Copy</button><button className="danger" onClick={()=>del.mutate(item.id)}>Delete</button></footer></article>)}</section></main>}
